#!/bin/bash

# ตรวจสอบสิทธิ์ Root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this script as root (e.g., using sudo)."
  exit 1
fi

echo "========================================="
echo "  SNMP Installation Script               "
echo "========================================="

# 1. รับค่าจากผู้ใช้
read -p "Enter SNMP Community String [default: public]: " INPUT_COMMUNITY </dev/tty
COMMUNITY_STRING=${INPUT_COMMUNITY:-public}

SYS_LOCATION="Datacenter"
SYS_CONTACT="admin@yourdomain.com"

echo ""
echo "=> Community String : $COMMUNITY_STRING"
echo "=> Allowed IP       : Any (default)"
echo "=> View Access      : systemonly (.1)"
echo "========================================="
echo "Detecting Operating System..."

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    OS_LIKE=$ID_LIKE
else
    echo "Cannot detect OS. /etc/os-release not found."
    exit 1
fi

echo "OS Detected: $OS"

# 2. ติดตั้ง Package ตาม OS
if [[ "$OS" == "ubuntu" || "$OS" == "debian" || "$OS_LIKE" == *"debian"* ]]; then
    echo "Installing SNMP on Debian/Ubuntu-based system..."
    apt-get update -y
    apt-get install -y snmpd snmp
    SVC_NAME="snmpd"

elif [[ "$OS" == "centos" || "$OS" == "rhel" || "$OS" == "almalinux" || "$OS" == "rocky" || "$OS" == "fedora" || "$OS_LIKE" == *"rhel"* || "$OS_LIKE" == *"fedora"* ]]; then
    echo "Installing SNMP on RHEL/CentOS-based system..."
    if command -v dnf >/dev/null 2>&1; then
        dnf install -y net-snmp net-snmp-utils
    else
        yum install -y net-snmp net-snmp-utils
    fi
    SVC_NAME="snmpd"

elif [[ "$OS" == "sles" || "$OS" == "opensuse"* || "$OS_LIKE" == *"suse"* ]]; then
    echo "Installing SNMP on SUSE-based system..."
    zypper -n install net-snmp
    SVC_NAME="snmpd"

else
    echo "Unsupported OS: $OS"
    exit 1
fi

# 3. ตั้งค่า SNMP Config
CONF_FILE="/etc/snmp/snmpd.conf"
echo "Configuring SNMP at $CONF_FILE..."

# Backup ไฟล์เดิม
if [ -f "$CONF_FILE" ]; then
    BACKUP_FILE="${CONF_FILE}.bak_$(date +%F_%H-%M-%S)"
    cp "$CONF_FILE" "$BACKUP_FILE"
    echo "Backed up original config to $BACKUP_FILE"
fi

# สร้างไฟล์ Config ใหม่ตามที่กำหนด
cat <<EOF > "$CONF_FILE"
# SNMP Configuration generated by script
# Listen on IPv4 and IPv6 localhost
agentAddress udp:161,[::1]

# --- Security & Access Control ---
# Create a view named 'systemonly' that includes the entire OID tree (.1)
view systemonly included .1

# Allow read-only access for any IP using the community string and the 'systemonly' view
rocommunity $COMMUNITY_STRING default -V systemonly

# --- System Information ---
sysLocation $SYS_LOCATION
sysContact $SYS_CONTACT

# --- System Metrics ---
# (Commented out) ตรวจสอบพื้นที่ Disk และ CPU Load Average
# includeAllDisks 10%
# load 12 10 5

# --- Logging ---
# ลดการเขียน Log ทุกครั้งที่ Monitoring Server เข้ามาดึงข้อมูล
dontLogTCPWrappersConnects yes
EOF

# 4. Enable และ Restart Service
echo "Enabling and restarting $SVC_NAME service..."
systemctl enable $SVC_NAME
systemctl restart $SVC_NAME

# 5. ตรวจสอบสถานะและทดสอบ
if systemctl is-active --quiet $SVC_NAME; then
    echo -e "\n✅ SNMP service installed and running successfully."
    echo "Community String: $COMMUNITY_STRING"
    echo "Port: UDP 161, [::1]:161"
    
    echo -e "\n========================================="
    echo "Running self-test: snmpwalk -v2c -c $COMMUNITY_STRING localhost system"
    echo "========================================="
    snmpwalk -v2c -c "$COMMUNITY_STRING" localhost system
    echo "========================================="

else
    echo -e "\n❌ Warning: SNMP service failed to start. Please check 'systemctl status $SVC_NAME'."
fi
