#!/bin/bash

# ตรวจสอบสิทธิ์ Root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this script as root (e.g., using sudo)."
  exit 1
fi

echo "========================================="
echo "  SNMP Installation Script (Bulletproof) "
echo "========================================="

# 1. รับค่าจากผู้ใช้ และกรองอักขระพิเศษ (CRLF) ที่อาจติดมาจากการ Copy
read -p "Enter SNMP Community String [default: public]: " INPUT_COMMUNITY </dev/tty
INPUT_COMMUNITY=$(echo "$INPUT_COMMUNITY" | tr -d '\r')
COMMUNITY_STRING=${INPUT_COMMUNITY:-public}

SYS_LOCATION="Datacenter"
SYS_CONTACT="admin@yourdomain.com"

echo ""
echo "=> Community String : $COMMUNITY_STRING"
echo "=> Allowed IP       : Any (default)"
echo "=> View Access      : systemonly (.1)"
echo "========================================="
echo "Detecting Operating System..."

# รองรับการตรวจจับ OS รุ่นเก่า (เช่น Ubuntu 14)
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    OS_LIKE=$ID_LIKE
elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    OS=$(echo $DISTRIB_ID | tr '[:upper:]' '[:lower:]')
else
    echo "Cannot detect OS."
    exit 1
fi

echo "OS Detected: $OS"

# 2. ติดตั้ง Package
if [[ "$OS" == *"ubuntu"* || "$OS" == *"debian"* || "$OS_LIKE" == *"debian"* ]]; then
    echo "Installing SNMP on Debian/Ubuntu-based system..."
    apt-get update -y
    apt-get install -y snmpd snmp
    SVC_NAME="snmpd"
elif [[ "$OS" == *"centos"* || "$OS" == *"rhel"* || "$OS_LIKE" == *"rhel"* ]]; then
    echo "Installing SNMP on RHEL/CentOS-based system..."
    if command -v dnf >/dev/null 2>&1; then
        dnf install -y net-snmp net-snmp-utils
    else
        yum install -y net-snmp net-snmp-utils
    fi
    SVC_NAME="snmpd"
else
    echo "Unsupported OS: $OS"
    exit 1
fi

# 3. ตั้งค่า SNMP Config
CONF_FILE="/etc/snmp/snmpd.conf"
echo "Configuring SNMP at $CONF_FILE..."

# Backup ไฟล์เดิม
if [ -f "$CONF_FILE" ]; then
    BACKUP_FILE="${CONF_FILE}.bak_$(date +%F_%H-%M-%S)"
    cp "$CONF_FILE" "$BACKUP_FILE"
    echo "Backed up original config to $BACKUP_FILE"
fi

# สร้างไฟล์ Config ใหม่ด้วยวิธี echo ทีละบรรทัด (ป้องกันปัญหา EOF พังจากการ Copy)
echo "# SNMP Configuration generated by script" > "$CONF_FILE"
echo "agentAddress udp:161,[::1]" >> "$CONF_FILE"
echo "" >> "$CONF_FILE"
echo "# --- Security & Access Control ---" >> "$CONF_FILE"
echo "view systemonly included .1" >> "$CONF_FILE"
echo "rocommunity $COMMUNITY_STRING default -V systemonly" >> "$CONF_FILE"
echo "" >> "$CONF_FILE"
echo "# --- System Information ---" >> "$CONF_FILE"
echo "sysLocation $SYS_LOCATION" >> "$CONF_FILE"
echo "sysContact $SYS_CONTACT" >> "$CONF_FILE"
echo "" >> "$CONF_FILE"
echo "# --- Logging ---" >> "$CONF_FILE"
echo "dontLogTCPWrappersConnects yes" >> "$CONF_FILE"

# 4. Enable และ Restart Service (รองรับ Ubuntu 14 ที่ไม่มี systemctl)
echo "Enabling and restarting $SVC_NAME service..."

if command -v systemctl >/dev/null 2>&1; then
    # สำหรับ OS สมัยใหม่
    systemctl enable $SVC_NAME
    systemctl restart $SVC_NAME
    STATUS_CMD="systemctl is-active --quiet $SVC_NAME"
else
    # สำหรับ OS เก่า เช่น Ubuntu 14 / CentOS 6
    if command -v update-rc.d >/dev/null 2>&1; then
        update-rc.d $SVC_NAME defaults
    elif command -v chkconfig >/dev/null 2>&1; then
        chkconfig $SVC_NAME on
    fi
    service $SVC_NAME restart
    STATUS_CMD="service $SVC_NAME status"
fi

# 5. ตรวจสอบสถานะและทดสอบ
if $STATUS_CMD >/dev/null 2>&1; then
    echo -e "\n✅ SNMP service installed and running successfully."
    echo "Community String: $COMMUNITY_STRING"
    echo "Port: UDP 161, [::1]:161"
    
    echo -e "\n========================================="
    echo "Running self-test: snmpwalk -v2c -c $COMMUNITY_STRING localhost system"
    echo "========================================="
    snmpwalk -v2c -c "$COMMUNITY_STRING" localhost system
    echo "========================================="
else
    echo -e "\n❌ Warning: SNMP service failed to start. Please check service status."
fi
